Repository Java-prog-class-2019/slate, pull requests merged in 2019-10, with the labels that each got.

#7 add items
  bin/main/.gitignore
  bin/main/Slate.g4
  src/main/java/slate/items/Apple.java
  src/main/java/slate/items/Avocado.java
  src/main/java/slate/items/Beaker.java
  src/main/java/slate/items/InvisibilityCloak.java
  src/main/java/slate/items/Key.java
  src/main/java/slate/items/LogBook.java
  src/main/java/slate/items/Muffin.java
  src/main/java/slate/items/Pen.java
  src/main/java/slate/items/Poison.java
  src/main/java/slate/items/Sword.java
Labels: enhancement

#8 Add navigation system
  bin/main/slate/App.class
  bin/main/slate/bases/ItemBase.class
  bin/main/slate/bases/MapBase.class
  bin/main/slate/bases/RoomBase.class
  bin/main/slate/maps/TestMap.class
  bin/main/slate/rooms/TestRoom.class
  src/main/java/slate/App.java
  src/main/java/slate/Navigator.java
  src/main/java/slate/bases/ItemBase.java
  src/main/java/slate/bases/MapBase.java
  src/main/java/slate/bases/RoomBase.java
  src/main/java/slate/maps/TestMap.java
  src/main/java/slate/prototypes/INavigator.java
  src/main/java/slate/rooms/TestRoom.java
Labels: enhancement

#10 Refactor rooms to match new system
  src/main/java/slate/rooms/BreakRoom.java
  src/main/java/slate/rooms/Elevator.java
  src/main/java/slate/rooms/Hallway.java
  src/main/java/slate/rooms/Laboratory.java
  src/main/java/slate/rooms/StartRoom.java
  src/main/java/slate/rooms/StorageRoom.java
  src/main/java/slate/rooms/Vault.java
Labels: enhancement

#9 Added Command Objects
  .idea/modules/slate.test.iml
  src/main/java/slate/App.java
  src/main/java/slate/parser/Command.java
  src/main/java/slate/parser/Commands.java
  src/main/java/slate/parser/Context.java
  src/main/java/slate/parser/ParserTest.java
  src/main/java/slate/parser/Slate.interp
  src/main/java/slate/parser/Slate.tokens
  src/main/java/slate/parser/SlateLexer.interp
  src/main/java/slate/parser/SlateLexer.java
  src/main/java/slate/parser/SlateLexer.tokens
  src/main/java/slate/parser/SlateParser.java
  src/main/resources/commands/CommandUsage.slateinfo
  src/main/resources/commands/Slate.g4
Labels: enhancement

#11 Beautiful grammar
  src/main/java/slate/parser/Command.java
  src/main/java/slate/parser/Commands.java
  src/main/java/slate/parser/Context.java
  src/main/java/slate/parser/Slate.interp
  src/main/java/slate/parser/Slate.tokens
  src/main/java/slate/parser/SlateBaseListener.java
  src/main/java/slate/parser/SlateBaseVisitor.java
  src/main/java/slate/parser/SlateLexer.interp
  src/main/java/slate/parser/SlateLexer.java
  src/main/java/slate/parser/SlateLexer.tokens
  src/main/java/slate/parser/SlateListener.java
  src/main/java/slate/parser/SlateParser.java
  src/main/java/slate/parser/SlateVisitor.java
  src/main/resources/commands/CommandUsage.slateinfo
  src/main/resources/commands/Slate.g4
Labels: enhancement

#12 Added player obj
  src/main/java/slate/Player.java
Labels: enhancement

#13 Navigational Commands
  .idea/uiDesigner.xml
  src/main/java/slate/App.java
  src/main/java/slate/bases/RoomBase.java
  src/main/java/slate/maps/TestMap.java
  src/main/java/slate/parser/Command.java
  src/main/java/slate/parser/Commands.java
  src/main/java/slate/parser/Context.java
  src/main/java/slate/parser/Slate.interp
  src/main/java/slate/parser/SlateLexer.interp
  src/main/java/slate/parser/SlateLexer.java
  src/main/java/slate/parser/SlateParser.java
  src/main/resources/commands/CommandUsage.slateinfo
  src/main/resources/commands/Slate.g4
Labels: enhancement

#17 Very Large Inventory Command System
  .idea/artifacts/Gradle___slate_war.xml
  .idea/artifacts/Gradle___slate_war__exploded_.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules/slate.main.iml
  src/main/java/slate/App.java
  src/main/java/slate/Inventory.java
  src/main/java/slate/Player.java
  src/main/java/slate/bases/ItemBase.java
  src/main/java/slate/bases/RoomBase.java
  src/main/java/slate/items/Apple.java
  src/main/java/slate/items/Avocado.java
  src/main/java/slate/items/InvisibilityCloak.java
  src/main/java/slate/items/TestItem.java
  src/main/java/slate/parser/Command.java
  src/main/java/slate/parser/Commands.java
  src/main/java/slate/parser/Context.java
  src/main/java/slate/parser/Slate.interp
  src/main/java/slate/parser/Slate.tokens
  src/main/java/slate/parser/SlateBaseListener.java
  src/main/java/slate/parser/SlateBaseVisitor.java
  src/main/java/slate/parser/SlateLexer.interp
  src/main/java/slate/parser/SlateLexer.java
  src/main/java/slate/parser/SlateLexer.tokens
  src/main/java/slate/parser/SlateListener.java
  src/main/java/slate/parser/SlateParser.java
  src/main/java/slate/parser/SlateVisitor.java
  src/main/java/slate/rooms/TestRoom.java
  src/main/resources/commands/CommandUsage.slateinfo
  src/main/resources/commands/Slate.g4
Labels: enhancement

#19 Fixed Item Subclass Method Overrides and Added empty search case
  src/main/java/slate/items/Beaker.java
  src/main/java/slate/items/Key.java
  src/main/java/slate/items/LogBook.java
  src/main/java/slate/items/Muffin.java
  src/main/java/slate/items/Pen.java
  src/main/java/slate/items/Poison.java
  src/main/java/slate/items/Sword.java
  src/main/java/slate/items/TestItem.java
  src/main/java/slate/parser/Command.java
Labels: bug, enhancement

#24 Guards
  src/main/java/slate/App.java
  src/main/java/slate/Guard.java
  src/main/java/slate/bases/MapBase.java
  src/main/java/slate/bases/RoomBase.java
  src/main/java/slate/maps/TestMap.java
  src/main/java/slate/parser/Command.java
  src/main/java/slate/parser/Commands.java
  src/main/java/slate/parser/Context.java
  src/main/java/slate/parser/Slate.interp
  src/main/java/slate/parser/Slate.tokens
  src/main/java/slate/parser/SlateBaseListener.java
  src/main/java/slate/parser/SlateBaseVisitor.java
  src/main/java/slate/parser/SlateLexer.interp
  src/main/java/slate/parser/SlateLexer.java
  src/main/java/slate/parser/SlateLexer.tokens
  src/main/java/slate/parser/SlateListener.java
  src/main/java/slate/parser/SlateParser.java
  src/main/java/slate/parser/SlateVisitor.java
  src/main/java/slate/rooms/TestRoom.java
  src/main/resources/commands/CommandUsage.slateinfo
  src/main/resources/commands/Slate.g4
Labels: bug, enhancement

#26 Lock System
  .idea/artifacts/slate_jar.xml
  build.gradle
  out/production/resources/commands/CommandUsage.slateinfo
  out/production/resources/commands/Slate.g4
  out/production/resources/story/introduction.txt
  src/main/java/slate/App.java
  src/main/java/slate/Inventory.java
  src/main/java/slate/META-INF/MANIFEST.MF
  src/main/java/slate/bases/MysteryBase.java
  src/main/java/slate/parser/Command.java
  src/main/java/slate/rooms/TestRoom.java
Labels: enhancement

#27 Finished first floor
  src/main/java/slate/App.java
  src/main/java/slate/bases/RoomBase.java
  src/main/java/slate/maps/GameMap.java
Labels: enhancement

#28 Add the rest of the rooms
  src/main/java/slate/maps/GameMap.java
Labels: enhancement

#34 Added items to rooms
  src/main/java/slate/Inventory.java
  src/main/java/slate/bases/RoomBase.java
  src/main/java/slate/items/Artifact.java
  src/main/java/slate/maps/GameMap.java
  src/main/java/slate/parser/Command.java
Labels: enhancement

#36 Guard Spawning + Bug Fixes
  src/main/java/slate/Guard.java
  src/main/java/slate/Player.java
  src/main/java/slate/bases/RoomBase.java
  src/main/java/slate/maps/GameMap.java
  src/main/java/slate/parser/Command.java
Labels: bug, enhancement

#38 Absolutely Gargantuan Update
  src/main/java/slate/App.java
  src/main/java/slate/Guard.java
  src/main/java/slate/Inventory.java
  src/main/java/slate/Navigator.java
  src/main/java/slate/Player.java
  src/main/java/slate/Room.java
  src/main/java/slate/bases/ItemBase.java
  src/main/java/slate/bases/MapBase.java
  src/main/java/slate/items/Apple.java
  src/main/java/slate/items/Artifact.java
  src/main/java/slate/items/Avocado.java
  src/main/java/slate/items/Beaker.java
  src/main/java/slate/items/InvisibilityCloak.java
  src/main/java/slate/items/Key.java
  src/main/java/slate/items/LogBook.java
  src/main/java/slate/items/Muffin.java
  src/main/java/slate/items/Pen.java
  src/main/java/slate/items/Poison.java
  src/main/java/slate/items/Sword.java
  src/main/java/slate/items/TestItem.java
  src/main/java/slate/maps/GameMap.java
  src/main/java/slate/maps/TestMap.java
  src/main/java/slate/parser/Command.java
  src/main/java/slate/parser/Commands.java
  src/main/java/slate/parser/Context.java
  src/main/java/slate/parser/Slate.interp
  src/main/java/slate/parser/Slate.tokens
  src/main/java/slate/parser/SlateBaseListener.java
  src/main/java/slate/parser/SlateBaseVisitor.java
  src/main/java/slate/parser/SlateLexer.interp
  src/main/java/slate/parser/SlateLexer.java
  src/main/java/slate/parser/SlateLexer.tokens
  src/main/java/slate/parser/SlateListener.java
  src/main/java/slate/parser/SlateParser.java
  src/main/java/slate/parser/SlateVisitor.java
  src/main/java/slate/prototypes/INavigator.java
  src/main/java/slate/rooms/BreakRoom.java
  src/main/java/slate/rooms/Elevator.java
  src/main/java/slate/rooms/Hallway.java
  src/main/java/slate/rooms/Laboratory.java
  src/main/java/slate/rooms/StartRoom.java
  src/main/java/slate/rooms/StorageRoom.java
  src/main/java/slate/rooms/TestRoom.java
  src/main/java/slate/rooms/Vault.java
  src/main/resources/commands/CommandUsage.slateinfo
  src/main/resources/commands/Slate.g4
Labels: bug, enhancement, housekeeping

#40 Lab Items
  src/main/java/slate/App.java
  src/main/java/slate/Guard.java
  src/main/java/slate/Room.java
  src/main/java/slate/bases/ItemBase.java
  src/main/java/slate/bases/MapBase.java
  src/main/java/slate/items/Apple.java
  src/main/java/slate/items/Avocado.java
  src/main/java/slate/items/Chemical.java
  src/main/java/slate/items/LogBook.java
  src/main/java/slate/items/Muffin.java
  src/main/java/slate/items/PlayerItem.java
  src/main/java/slate/items/Radio.java
  src/main/java/slate/items/Sword.java
  src/main/java/slate/maps/GameMap.java
  src/main/java/slate/maps/TestMap.java
  src/main/java/slate/parser/Command.java
  src/main/resources/story/breakroomc.logbook
  src/main/resources/story/laba1.logbook
  src/main/resources/story/laba2.logbook
  src/main/resources/story/labb.logbook
Labels: bug, enhancement

#41 Game can be both won and lost
  src/main/java/slate/App.java
  src/main/java/slate/Guard.java
  src/main/java/slate/Player.java
  src/main/java/slate/bases/ItemBase.java
  src/main/java/slate/items/Apple.java
  src/main/java/slate/items/Avocado.java
  src/main/java/slate/items/Chemical.java
  src/main/java/slate/items/Muffin.java
  src/main/java/slate/items/Pen.java
  src/main/java/slate/items/PlayerItem.java
  src/main/java/slate/items/StickyBaby.java
  src/main/java/slate/maps/GameMap.java
  src/main/java/slate/parser/Command.java
  src/main/java/slate/parser/Commands.java
Labels: bug, enhancement

#42 Add packaging script
  .gitignore
  Makefile
  build.gradle
  src/main/java/slate/App.java
Labels: enhancement

#47 Added comments for everything
  build.gradle
  docs/constant-values.html
  docs/deprecated-list.html
  docs/index-all.html
  docs/slate/parser/SlateBaseListener.html
  docs/slate/parser/SlateBaseVisitor.html
  docs/slate/parser/SlateLexer.html
  docs/slate/parser/SlateListener.html
  docs/slate/parser/SlateParser.CheckdoorscommContext.html
  docs/slate/parser/SlateParser.ClosecommContext.html
  docs/slate/parser/SlateParser.ExitcommContext.html
  docs/slate/parser/SlateParser.HelpcommContext.html
  docs/slate/parser/SlateParser.LeavecommContext.html
  docs/slate/parser/SlateParser.MovecommContext.html
  docs/slate/parser/SlateParser.OpencommContext.html
  docs/slate/parser/SlateParser.PeekcommContext.html
  docs/slate/parser/SlateParser.PickupcommContext.html
  docs/slate/parser/SlateParser.SaycommContext.html
  docs/slate/parser/SlateParser.SearchcommContext.html
  docs/slate/parser/SlateParser.ShoutcommContext.html
  docs/slate/parser/SlateParser.SuperlongcommContext.html
  docs/slate/parser/SlateParser.UsecommContext.html
  docs/slate/parser/SlateParser.WaitcommContext.html
  docs/slate/parser/SlateParser.html
  docs/slate/parser/SlateVisitor.html
  src/main/java/slate/Util.java
  src/main/java/slate/bases/Direction.java
  src/main/java/slate/bases/ItemBase.java
  src/main/java/slate/bases/MapBase.java
  src/main/java/slate/items/Chemical.java
  src/main/java/slate/items/InvisibilityCloak.java
  src/main/java/slate/items/LogBook.java
  src/main/java/slate/items/PlayerItem.java
  src/main/java/slate/items/Poison.java
  src/main/java/slate/items/StickyBaby.java
  src/main/java/slate/parser/Command.java
  src/main/java/slate/parser/Commands.java
  src/main/java/slate/parser/Context.java
  src/main/java/slate/parser/antlrgen/Slate.interp
  src/main/java/slate/parser/antlrgen/Slate.tokens
  src/main/java/slate/parser/antlrgen/SlateBaseListener.java
  src/main/java/slate/parser/antlrgen/SlateBaseVisitor.java
  src/main/java/slate/parser/antlrgen/SlateLexer.interp
  src/main/java/slate/parser/antlrgen/SlateLexer.java
  src/main/java/slate/parser/antlrgen/SlateLexer.tokens
  src/main/java/slate/parser/antlrgen/SlateListener.java
  src/main/java/slate/parser/antlrgen/SlateParser.java
  src/main/java/slate/parser/antlrgen/SlateVisitor.java
  src/main/java/slate/prototypes/INavigator.java
  src/main/resources/story/introduction.txt
Labels: documentation, enhancement
